### PR TITLE
[PLATFORM-1005]: Fix compilation failure due to absinthe being optional

### PR DESCRIPTION
**Pull request by MaeIsBad**
https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PLATFORM-1005

### CODE REVIEW

**Comment by MaeIsBad** [comment]
Prima_opentelemetry_ex for example unconditionally includes it, even if the project doesn't use graphql

I would prefer just depending on absinthe, but I think this is fine for compatibility

**Comment by cpiemontese** [comment]
I see, I wonder if we should issue an `IO.warn` or something if absinthe is not enabled, so as not to be silent that we are configuring a "dummy" handler

**Comment by MaeIsBad** [comment]
> I see, I wonder if we should issue an IO.warn or something if absinthe is not enabled, so as not to be silent that we are configuring a "dummy" handler

I guess we can do that? But then do we just deprecate using this library without absinthe?

**Comment by cpiemontese** [comment]
Since this library instruments absinthe, if someone uses it without including absinthe and nothing breaks but also nothing works (silently) then it's a bit strange. That's why I would at least `warn`.

That said I was wondering: can't we set `opentelemetry_absinthe` optional on `prima_opentelemetry_ex`...? I don't know if it would work the same, but it could make sense to make the use implicitly import an optional dependency for additional usage

**Comment by MaeIsBad** [comment]
> That said I was wondering: can't we set opentelemetry_absinthe optional on prima_opentelemetry_ex...? I don't know if it would work the same, but it could make sense to make the use implicitly import an optional dependency for additional usage

Sure that makes sense to me. It will be a breaking change on prima_opentelemetry_ex, since it will require people using absinthe to add opentelemetry_absinthe as a dependency themselves, but I think it's a good idea. While we're at it I think we can also make teleplug and telepoison optional dependencies of prima_opentelemetry_ex

**Comment by cpiemontese** [comment]
I guess it makes sense! It's breaking but at the same time it's more explicit about which feature one wants to use and it doesn't install useless stuff

**Comment by MaeIsBad** [comment]
changed this PR to make absinthe a required dependency and added a note to the changelog

**Review by cpiemontese — APPROVED** [review]

**Pull request merged**
