### PR TITLE
[PLATFORM-1689]: Attach to subscription publish events

### PR DESCRIPTION
**Pull request by cpiemontese**
https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PLATFORM-1689

### CODE REVIEW

**Comment by cpiemontese** [comment]
This will close https://github.com/primait/opentelemetry_absinthe/pull/145

**Review by MaeIsBad — APPROVED** [review]
Actually should we keep this behind a feature flag?

**Comment by cpiemontese** [comment]
@MaeIsBad I made it optional behind a flag and refactor the code to make it more testable

**Review by MaeIsBad — APPROVED** [review]
:tada:

**Pull request merged**
